title: HD2MM
email: FloCo12@gmx.net
github_username: teutinsa
url: "https://teutinsa.github.io"
baseurl: "/hd2mm-site"

highlighter: rouge

collections_dir: collections
collections:
  faq:
    order:
      - not_starting.md
    output: true
    permalink: /help/:collection/:name:output_ext

defaults:
  - scope:
      path: ""
      type: faq
    values:
      layout: faq

plugins:
  - jekyll-feed