title: HD2MM
email: FloCo12@gmx.net
github_username: teutinsa
url: "https://teutinsa.github.io"
baseurl: "/hd2mm-site"

highlighter: rouge

collections_dir: collections
collections:
  - faq

plugins:
  - jekyll-feed